Repository Rebels-Y3S2/STOP-SMOKING-MOBILE, pull requests merged in 2022-11, with the labels that each got.

#28 Integrated view reminders functionality
  src/api/reminder.api.js
  src/components/Card/CardStyles.js
  src/pages/Reminder Management/Reminders/Reminders.js
  src/pages/Reminder Management/Reminders/RemindersStyles.js
Labels: enhancement, Feature

#38 Feature/reminder
  package.json
  src/api/reminder.api.js
  src/components/DialogBox/DialogBox.js
  src/components/DropDown/DropDown.js
  src/components/DropDown/DropDownStyles.js
  src/components/PushNotifications/PushNotifications.js
  src/navigation/stackNavigator.js
  src/pages/Reminder Management/Create Reminder/CreateReminder.js
  src/pages/Reminder Management/Reminders/Reminders.js
  src/pages/Reminder Management/Reminders/RemindersStyles.js
  src/pages/Reminder Management/Update Reminder/UpdateReminder.js
  src/pages/Reminder Management/Update Reminder/UpdateReminderStyles.js
  src/util/Constants/CommonConstants.js
  src/util/Constants/ReminderConstants.js
Labels: enhancement, Feature

#31 Home user interface done
  package.json
  src/api/users.api.js
  src/components/DialogBox/DialogBoxQuickGuide.js
  src/components/DialogBox/DialogBoxUserDeletion.js
  src/navigation/TabNavigator.js
  src/navigation/stackNavigator.js
  src/pages/HomeStyles.js
  src/pages/UserProfile/UpdateProfile.js
  src/pages/UserProfile/UserLogin.js
  src/pages/UserProfile/UserProfileStyles.js
  src/pages/UserProfile/UserRegistration.js
  src/pages/UserProfile/ViewProfile.js
  src/pages/home.js
Labels: Feature

#68 Fixed delete issue in reminder feature
  src/localization/en/translation.json
  src/localization/sn/translation.json
  src/localization/tm/translation.json
  src/navigation/StackNavigator.js
  src/pages/Reminder Management/Context/ReminderContext.js
  src/pages/Reminder Management/Create Reminder/CreateReminder.js
  src/pages/Reminder Management/Reminders/Reminders.js
  src/pages/Reminder Management/Update Reminder/UpdateReminder.js
  src/util/Constants/CommonConstants.js
Labels: enhancement
